In [50]:
import json
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import numpy as np

In [27]:
tds = pd.read_json('yelp_academic_dataset_tip.json', lines = True)
bds = pd.read_json('yelp_academic_dataset_business.json', lines = True)
tds1 = tds.drop(['date', 'compliment_count', 'user_id'], axis = 1)
bds1 = bds.drop(['hours', 'is_open', 'review_count', 'latitude', 'longitude', 'postal_code', 'city', 'address', 'stars', 'name'], axis = 1)
merged = pd.merge(bds1, tds1, on = 'business_id')
merged

,business_id,state,attributes,categories,text
0,6iYb2HFDywm3zjuRg0shjw,CO,"{'RestaurantsTableService': 'True', 'WiFi': 'u...","Gastropubs, Food, Beer Gardens, Restaurants, B...",Good beers. Bad bartender. Stay away from Brian.
1,6iYb2HFDywm3zjuRg0shjw,CO,"{'RestaurantsTableService': 'True', 'WiFi': 'u...","Gastropubs, Food, Beer Gardens, Restaurants, B...",I enjoy this location. Great beers. Great serv...
2,6iYb2HFDywm3zjuRg0shjw,CO,"{'RestaurantsTableService': 'True', 'WiFi': 'u...","Gastropubs, Food, Beer Gardens, Restaurants, B...",Live music every week! Beer menus not yet prin...
3,6iYb2HFDywm3zjuRg0shjw,CO,"{'RestaurantsTableService': 'True', 'WiFi': 'u...","Gastropubs, Food, Beer Gardens, Restaurants, B...",Good food. Good crowd. The ranch taste very si...
4,6iYb2HFDywm3zjuRg0shjw,CO,"{'RestaurantsTableService': 'True', 'WiFi': 'u...","Gastropubs, Food, Beer Gardens, Restaurants, B...",The newest Oskar Blues opens this coming Monda...
...,...,...,...,...,...
1162114,ngmLL5Y5OT-bYHKU0kKrYA,FL,"{'RestaurantsReservations': 'True', 'OutdoorSe...","Restaurants, Middle Eastern, Mediterranean, Pe...",The shish kabab is the best. Make sure to try ...
1162115,ngmLL5Y5OT-bYHKU0kKrYA,FL,"{'RestaurantsReservations': 'True', 'OutdoorSe...","Restaurants, Middle Eastern, Mediterranean, Pe...",Excellent Mediterranean food! Just like in Bo...
1162116,ngmLL5Y5OT-bYHKU0kKrYA,FL,"{'RestaurantsReservations': 'True', 'OutdoorSe...","Restaurants, Middle Eastern, Mediterranean, Pe...",Exceptional taste from real charcoal. We had t...
1162117,ngmLL5Y5OT-bYHKU0kKrYA,FL,"{'RestaurantsReservations': 'True', 'OutdoorSe...","Restaurants, Middle Eastern, Mediterranean, Pe...",Great food!!!
1162118,ngmLL5Y5OT-bYHKU0kKrYA,FL,"{'RestaurantsReservations': 'True', 'OutdoorSe...","Restaurants, Middle Eastern, Mediterranean, Pe...",Stopped by on a whim and so glad that we did!!...

## Task 1

In [37]:
#### Task 1a

In [39]:
from textblob import TextBlob
merged['sentiment'] = merged['text'].apply(lambda x: TextBlob(x).sentiment.polarity)

#### Task 1b

In [44]:
meanprep = merged.drop(['business_id', 'attributes', 'categories', 'text'], axis = 1)
statemeans = meanprep.groupby('state').mean()
statemeans

       sentiment
state
ABE     0.550000
AL     -0.350000
AZ      0.423214
BC      0.253967
CA      0.370000
CO      0.331751
DC      0.045055
DE      0.522917
FL      0.302845
GA      0.286886
IL      0.045000
KS      0.236806
KY      0.730000
MA      0.278255
NC      0.002778
NH      0.666667
OH      0.296958
OR      0.297553
TX      0.273197
VA      0.082540
WA      0.336497
WI      0.400000

#### Task 1c

In [49]:
import plotly
import plotly.graph_objects as go

fig = go.Figure(data=go.Choropleth(
    locations=statemeans['state'], # Spatial coordinates
    z = statemeans['sentiment'].astype(float), # Data to be color-coded
    locationmode = 'USA-states', # set of locations match entries in `locations`
    colorscale = 'Reds',
    colorbar_title = "Review Sentiment",
))

fig.update_layout(
    title_text = 'Sentiment of Yelp reviews by State',
    geo_scope='usa', # limite map scope to USA
)

fig.show()
#plotly.offline.plot(fig, filename='map.html')

KeyError: 'state'

## Task 2

#### Task 2a

In [62]:
MAds = merged.loc[merged['state'] == 'MA']
MAds1 = MAds[MAds['categories'].notna()]
MAds1['is_Restaurant'] = MAds1['categories'].apply(lambda x: 1 if 'Restaurants' in x else 0)
MAds1

,business_id,state,attributes,categories,text,sentiment,is_Restaurant
94,HPA_qyMEddpAEtFof02ixg,MA,"{'RestaurantsGoodForGroups': 'True', 'HasTV': ...","Food, Pizza, Restaurants",Homemade bread is out of this world,0.000000,1
95,HPA_qyMEddpAEtFof02ixg,MA,"{'RestaurantsGoodForGroups': 'True', 'HasTV': ...","Food, Pizza, Restaurants","So as I'm sitting here, I love the decor! Look...",0.257623,1
96,HPA_qyMEddpAEtFof02ixg,MA,"{'RestaurantsGoodForGroups': 'True', 'HasTV': ...","Food, Pizza, Restaurants",Don't use the bathroom. They keep the cornmeal...,-0.044444,1
97,HPA_qyMEddpAEtFof02ixg,MA,"{'RestaurantsGoodForGroups': 'True', 'HasTV': ...","Food, Pizza, Restaurants",The pizza here is delicious! My favorite in th...,0.600000,1
124,6fT0lYr_UgWSCZs_w1PBTQ,MA,None,"Specialty Schools, Massage Schools, Middle Sch...",Scam,0.000000,0
...,...,...,...,...,...,...,...
1161965,yQL8SrSETbbCI1U5esVJQw,MA,"{'GoodForKids': 'True', 'RestaurantsPriceRange...","Restaurants, Pizza, Italian",Best Pizza in Boston....Period.,1.000000,1
1161966,yQL8SrSETbbCI1U5esVJQw,MA,"{'GoodForKids': 'True', 'RestaurantsPriceRange...","Restaurants, Pizza, Italian",Food is good but small portions !,0.193750,1
1161967,yQL8SrSETbbCI1U5esVJQw,MA,"{'GoodForKids': 'True', 'RestaurantsPriceRange...","Restaurants, Pizza, Italian",Wow! Tiny place but the vibe was cool and past...,0.368750,1
1161968,yQL8SrSETbbCI1U5esVJQw,MA,"{'GoodForKids': 'True', 'RestaurantsPriceRange...","Restaurants, Pizza, Italian",Great creative oizza,0.650000,1
1161969,yQL8SrSETbbCI1U5esVJQw,MA,"{'GoodForKids': 'True', 'RestaurantsPriceRange...","Restaurants, Pizza, Italian",Excellent pasta and pizza ! First time ! Defin...,0.604167,1

#### Task 2b

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(MAds1['text'])
vectorizer.get_feature_names_out()

AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names_out'

#### Task 2c